name: Deploy Jekyll Site

on:
  push:
    branches:
      - main  # или ваша основная ветка

permissions:
  contents: write  # Требуется для деплоя в `gh-pages`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Или другая версия, поддерживающая Jekyll
          bundler-cache: true

      - name: Install Jekyll and dependencies
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Add CNAME file
        run: echo "msaidov.com" > _site/CNAME

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
          clean: true
